apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      container:
        name: nginx
        image: nginx
        port:
          - containerport: 80
        command: ["/bin/sh"]
        args: ["-c", "echo Hello from $(hostname -i) > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"]

