apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        command: ["/bin/sh"]
        args: ["-c", "echo Hello from $(hostname -i) > /usr/share/nginx/html/index.html && echo $(cat /usr/share/config/config_value) >> /usr/share/nginx/html/index.html && echo $(cat /usr/share/secret/secret_value) >> /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"]
        volumeMounts:
        - name: configmap-volume
          mountPath: /usr/share/config/
          readOnly: true  # Set to true as configmaps are readonly
        - name: secret-volume
          mountPath: /usr/share/secret/
          readOnly: true  # Set to true as secrets are readonly
        - name: pv-volume
          mountPath: /data  # Mounting PV to /data directory inside the container
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: configmap-volume
        configMap:
          name: configmap-volume
      - name: secret-volume
        secret:
          secretName: my-secret
      - name: pv-volume
        persistentVolumeClaim:
          claimName: my-pvc  # Assuming there is a PVC named my-pvc that binds to the PV
