apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 1Gi  # Capacity of the volume
  accessModes:
    - ReadWriteOnce  # Access mode
  persistentVolumeReclaimPolicy: Retain  # Policy for what happens to the volume when released
  hostPath:
    path: "/mnt/data"  # Path on the host filesystem to use for the volume
