apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Can be ReadWriteOnce, ReadOnlyMany, or ReadWriteMany
  resources:
    requests:
      storage: 1Gi  # Requested storage size
